# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable and overrides ENV variables in the Unix shell.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]
# Add application configuration variables here, as shown below.
#
GMAIL_USERNAME: arbreperdu@gmail.com
GMAIL_PASSWORD: ..FU.as.01..
ADMIN_NAME: Chris Dutton
ADMIN_EMAIL: chris@aquatic-edge.com
ADMIN_PASSWORD: 05test05
ROLES: [admin, silver, gold, platinum]
STRIPE_API_KEY: Your_Stripe_API_key
STRIPE_PUBLIC_KEY: Your_Stripe_Public_Key
amazon_access_key_id: AKIAJNOGJIXZ6YT34HUA
amazon_secret_access_key: TieFCpIcR2O6JuxGt9BLwoxksDakUvoCwn0myNsr

